// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trabalho;

#nullable disable

namespace trabalho.Migrations
{
    [DbContext(typeof(BaseAdocoes))]
    partial class BaseAdocoesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Trabalho.Adocao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("animalid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("userid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("animalid");

                    b.HasIndex("userid");

                    b.ToTable("Adocoes");
                });

            modelBuilder.Entity("Trabalho.Animal", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Animais");
                });

            modelBuilder.Entity("Trabalho.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Trabalho.Adocao", b =>
                {
                    b.HasOne("Trabalho.Animal", "animal")
                        .WithMany()
                        .HasForeignKey("animalid");

                    b.HasOne("Trabalho.Usuario", "user")
                        .WithMany()
                        .HasForeignKey("userid");

                    b.Navigation("animal");

                    b.Navigation("user");
                });
#pragma warning restore 612, 618
        }
    }
}
